# Generated by Django 3.2.8 on 2022-02-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companysearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysearch',
            old_name='user_id',
            new_name='email',
        ),
    ]
